-- 코드를 입력하세요
SELECT TITLE, 
       BOARD_ID, 
       REPLY_ID, 
       r.WRITER_ID, 
       r.CONTENTS, 
       TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r USING(BOARD_ID)
WHERE b.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') 
                         AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY r.CREATED_DATE ASC, TITLE ASC;