-- 코드를 입력하세요
SELECT TITLE, 
       b.BOARD_ID, 
       REPLY_ID, 
       r.WRITER_ID, 
       r.CONTENTS, 
       r.CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r USING(BOARD_ID)
WHERE YEAR(b.CREATED_DATE) = 2022 
  AND MONTH(b.CREATED_DATE) = 10
ORDER BY r.CREATED_DATE ASC, TITLE ASC;